spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_pub?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&useSSL=false&serverTimezone=Europe/Moscow&characterEncoding=utf8
    username: root
    password: 1234

  jpa:
    show-sql: true
    hibernate.ddl-auto: none

  properties:
    hibernate:
      jdbc.time_zone: Europe/Moscow
      dialect: org.hibernate.dialect.MySQL55Dialect
      globally_quoted_identifiers: true

  mvc:
    favicon.enabled: false

  liquibase.change-log: classpath:/db.changelog/db.changelog-master.yaml