spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:mysql://localhost:3306/dev_pub}
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:mysql://localhost:3306/dev_pub?serverTimezone=Europe/Moscow
    user: root
    password: 1234

  mail:
    # Логин и пароль пользователя от почты на gmail
    host: smtp.gmail.com
    port: 587
    username: devpubsocial@gmail.com
    password: DevPubSocial

upload:
  path: "upload"

captcha:
  lifetime: 60 #minutes

project.name: Социальная сеть разработчиков

init:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 926 787-77-73
  email: a.v.karmashov@gmail.com
  copyright: Андрей Кармашов
  copyrightFrom: 2020

server:
  port: ${PORT:8080}