spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev_pub?serverTimezone=Europe/Moscow
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

#  jpa:
#    show-sql: true
#    hibernate.ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:mysql://localhost:3306/dev_pub?serverTimezone=Europe/Moscow
    user: root
    password: 1234

  mail:
    # Логин и пароль пользователя от почты на gmail
    host: smtp.gmail.com
    port: 587
    username: devpubsocial@gmail.com
    password: DevPubSocial

upload:
  path: "D:/upload"

captcha:
  lifetime: 60 #minutes

project.name: Социальная сеть разработчиков

jwt.token:
  secret: jwtdevpubtoken
  expired: 36000000